### ISSUE TITLE
モチーフとなるカラースキーマの策定

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/okuru.yokohama#10]
プロダクト全般およびウェブサイト、SNSなどでの使用を想定し、以下カラースキーマを決定する。カラースキーマは各カラーについて16進法表記で利用できるように用意しREADMEに落としておく。

・プライマリカラー（１つ）
・セカンダリカラー（１つまたは２つ）
・アクセントカラー（１つまたは２つ）

**Comment by kyoyababa** [comment]
NOTE:
その他ウェブにおけるカラースキーマは明るさや彩度を適宜調整して別途constを立てる

**Comment by Kenta-Yahagi** [comment]
http://hue360.herokuapp.com/
今度どっかでこれ見ながら検討するってのはどうかな

**Comment by kyoyababa** [comment]
@Kenta-Yahagi 今週土曜日行けたらいく（信頼度10%）ので、そのときかな！

**Comment by Kenta-Yahagi** [comment]
そうね！
