### ISSUE TITLE
Facebookアカウントの作成とコンテンツの用意

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/okuru.yokohama#6]
LPからの動線としてFacebookアカウントを設けるなら必要。
また、そのアカウントからdeveloper API Keyなどを渡してもらわないといけない。

**Comment by Kenta-Yahagi** [comment]
ちょっと名前とかコンセプトを6月中にきめて、とりあえず作るかね。

**Comment by kyoyababa** [comment]
NOTE: これは矢萩にアサインすることになりそう

**Comment by Kenta-Yahagi** [comment]
ok

**Comment by kyoyababa** [comment]
NOTE: とるだけとっておく
