### ISSUE TITLE
スペースマーケットのアカウント開設とコンテンツの用意

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/okuru.yokohama#7]
LPからの動線として設けるなら必要。
スペースマーケット側のコンテンツが固まらないとLPに掲載する画像やテキストなどがアラインメントとれないので、優先度はけっこう高いかも。

**Comment by Kenta-Yahagi** [comment]
これもFB同様着手しよう。基本的にスペースマーケットはトシ君に先頭立ってもらおうかな。

**Comment by kyoyababa** [comment]
NOTE: issueの管理者は矢萩ということになりそう

**Comment by Kenta-Yahagi** [comment]
スペースマーケットはちょっと時間かかりそうなので。（てか8月オープンだけど、家オープンできるほど完成してない。）
Coming soon..で誤魔化したいです。とりあえず

**Comment by Kenta-Yahagi** [comment]
スペースマーケットはとりあえずまだやらない方向で調整した。(今はオーナーがいかにokuruを活用するかを最大化させたいフェーズなので。スペース貸し系はrevenue最適化や繋がりのない第三者を獲得していきたいフェーズに入ったときに行う。

**Comment by Kenta-Yahagi** [comment]
あとokuruの場所についてのサイトへの記載について。
あえて場所はサイトには載せないつもり。
その代わり、

okuruは「より多くの人に来てもらう」という思想ではなく、「自宅の様な居心地の良さ」を優先した運営をしております。
よってサイトには場所は記載していません
一度ご覧になりたい、もっと詳しく知りたい場合はこちら(メーラーが起動)にご連絡ください。

的な事は載せておく。
