### ISSUE TITLE
物件のロゴの用意

### ISSUE THREAD

**Issue by kyoyababa** [kyoyababa/okuru.yokohama#9]
・汎用性を考慮しSVGで出力できるようにAIで用意する。
・Facebookやその他SNSでの拡散性を考慮しプライマリカラーでPNGを用意

**Comment by kyoyababa** [comment]
NOTE: https://github.com/kyoyababa/tsunashima-house/issues/8 が整い次第、パターン出しをしてみんなで検討する

**Comment by Kenta-Yahagi** [comment]
ニャン
